from typing import Any, Protocol


class Renderer(Protocol):
    def frame_end(self) -> float: ...
    def poll_events(self) -> bool: ...
    def render(self, game: Any) -> None: ...
    def get_abstract_input(self) -> dict: ...
    def get_bounds(self) -> dict: ...
    def init_refs(self, player) -> None: ...
